nxLINEadmin/Controllers/AuthController.cs
using nxLINEadmin.Model;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using nxLINEadmin.UnitOfWork;
using nxLINEadmin.Utilities;
using nxLINEadmin.Entity;
using AutoMapper;
using Microsoft.AspNetCore.Identity;


namespace nxLINEadmin.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IMapper _mapper;
        protected string UserId
        {
            get
            {
                return User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
        }

        public AuthController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Login(string? returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new LoginUserViewModel());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Login(LoginUserViewModel user, string? returnUrl = null)
        {
            // here is test code
            // string s = returnUrl == null ? "/Home/" : returnUrl;
            if (!ModelState.IsValid)
                return View(user);

            var atUser = await _unitOfWork.UserRepos.GetByCondition(u => u.UserLoginId == user.UserLoginId).FirstOrDefaultAsync();

            if (atUser == null)
            {
                ModelState.AddModelError("", "ユーザー名またはパスワードが違います");
                return View(user);
            }

            // パスワードの比較
            if (!AuthHelper.CheckPasswordLogin(user.Password, atUser.UserPwd))
            {
                ModelState.AddModelError("", "ユーザー名またはパスワードが違います");
                return View(user);
            }

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, atUser.UserLoginId));

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

            string redirectUrl = returnUrl == null ? "/Home/" : returnUrl;

            return Redirect(redirectUrl);
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
        public IActionResult ForGot()
        {
            return View(new RegisterUserViewModel());
        }

        public IActionResult SendCode()
        {
            return View(new RegisterUserViewModel());
        }

        public IActionResult Register()
        {
            return View(new RegisterUserViewModel());
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Register(RegisterUserViewModel user)
        {
            if (!ModelState.IsValid)
                return View(user);

            if (user.UserRePwd != user.UserPwd)
            {
                ModelState.AddModelError("", "値が違います");
                return View(user);
            }
                
            var atUser = await _unitOfWork.UserRepos.GetByCondition(u => u.UserLoginId == user.UserLoginId).FirstOrDefaultAsync();

            if (atUser != null)
            {
                ModelState.AddModelError("", "その名前はすでに使用されています");
                return View(user);
            }

            atUser = await _unitOfWork.UserRepos.GetByCondition(u => u.UserEmail == user.UserEmail).FirstOrDefaultAsync();

            if (atUser != null)
            {
                ModelState.AddModelError("", "そのメールアドレスは既に使用されています");
                return View(user);
            }
            User model = new User();

            model.UserName = user.UserName;
            model.UserLoginId = user.UserLoginId;
            model.UserEmail = user.UserEmail;
            model.UserPwd = AuthHelper.HashPassword(user.UserPwd);

            model.UserCreated = DateTime.Now;
            _unitOfWork.UserRepos.Add(model);
            _unitOfWork.Complete();

            return RedirectToAction("Login");
        }
    }
}

nxLINEadmin/Controllers/SettingController.cs
using nxLINEadmin.Model;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using nxLINEadmin.UnitOfWork;
using nxLINEadmin.Entity;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using nxLINEadmin.Utilities;

namespace nxLINEadmin.Controllers
{
    public class SettingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _contextAccessor;
        
        private string _userID;

        public static string noImgUrl = "/images/no_image.jpeg";

        public SettingController(
            IWebHostEnvironment hostingEnvironment,
            IUnitOfWork unitOfWork, 
            IHttpContextAccessor contextAccessor,
            IMapper mapper
            )
        {
            _unitOfWork = unitOfWork;
            _contextAccessor = contextAccessor;
            _hostingEnvironment = hostingEnvironment;
            _mapper = mapper;

            var httpContext = _contextAccessor.HttpContext;
            var user = httpContext.User;
            _userID = user.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        public async Task<IActionResult> Basic(string errorType = "", string errorMsg = "")
        {
            User currentUser = await _unitOfWork.UserRepos.FindUserAsync(_userID);
            int lineAccountID = currentUser.UserLineAccountID ?? 0;
            LineAccount lineAccount;

            if (lineAccountID == 0)
            {
                lineAccount = new LineAccount();
                lineAccount.LineaccountCode = "1";
                lineAccount.LineaccountShortcode = "1";
                lineAccount.LineaccountEmail = currentUser.UserEmail;
                lineAccount.LineaccountCreated = DateTime.Now;

                _unitOfWork.LineAccountRepos.Add(lineAccount);
                _unitOfWork.Complete();

                int newLineID = lineAccount.LineaccountId;
                currentUser.UserLineAccountID = newLineID;
                currentUser.UserUpdated = DateTime.Now;
                _unitOfWork.UserRepos.Update(currentUser);
                _unitOfWork.Complete();
            }
            else
            {
                lineAccount = _unitOfWork.LineAccountRepos.GetById(lineAccountID);
            }

            SettingViewModel vm = new SettingViewModel();
            vm.Account = lineAccount;
            vm.newUser = new RegisterUserViewModel();

            ViewBag.errorType = errorType; 
            ViewBag.errorMsg = errorMsg;

            List<User> users = _unitOfWork.UserRepos.GetAll().ToList();
            vm.Users = users;
            return View(vm);
        }
        public async Task<IActionResult> Membership(string errorType = "", string errorMsg = "")
        {
            User currentUser = await _unitOfWork.UserRepos.FindUserAsync(_userID);
            int lineAccountID = currentUser.UserLineAccountID ?? 0;
            LineAccount lineAccount;

            if (lineAccountID == 0)
            {
                lineAccount = new LineAccount();
                lineAccount.LineaccountCode = "1";
                lineAccount.LineaccountShortcode = "1";
                lineAccount.LineaccountEmail = currentUser.UserEmail;
                lineAccount.LineaccountCreated = DateTime.Now;

                _unitOfWork.LineAccountRepos.Add(lineAccount);
                _unitOfWork.Complete();

                int newLineID = lineAccount.LineaccountId;
                currentUser.UserLineAccountID = newLineID;
                currentUser.UserUpdated = DateTime.Now;
                _unitOfWork.UserRepos.Update(currentUser);
                _unitOfWork.Complete();
            }
            else
            {
                lineAccount = _unitOfWork.LineAccountRepos.GetById(lineAccountID);
            }

            SettingViewModel vm = new SettingViewModel();
            vm.Account = lineAccount;
            vm.newUser = new RegisterUserViewModel();

            ViewBag.errorType = errorType; 
            ViewBag.errorMsg = errorMsg;

            List<User> users = _unitOfWork.UserRepos.GetAll().ToList();
            vm.Users = users;
            return View(vm);
        }
        public async Task<IActionResult> Permission(string errorType = "", string errorMsg = "")
        {
            User currentUser = await _unitOfWork.UserRepos.FindUserAsync(_userID);
            int lineAccountID = currentUser.UserLineAccountID ?? 0;
            LineAccount lineAccount;

            if (lineAccountID == 0)
            {
                lineAccount = new LineAccount();
                lineAccount.LineaccountCode = "1";
                lineAccount.LineaccountShortcode = "1";
                lineAccount.LineaccountEmail = currentUser.UserEmail;
                lineAccount.LineaccountCreated = DateTime.Now;

                _unitOfWork.LineAccountRepos.Add(lineAccount);
                _unitOfWork.Complete();

                int newLineID = lineAccount.LineaccountId;
                currentUser.UserLineAccountID = newLineID;
                currentUser.UserUpdated = DateTime.Now;
                _unitOfWork.UserRepos.Update(currentUser);
                _unitOfWork.Complete();
            }
            else
            {
                lineAccount = _unitOfWork.LineAccountRepos.GetById(lineAccountID);
            }

            SettingViewModel vm = new SettingViewModel();
            vm.Account = lineAccount;
            vm.newUser = new RegisterUserViewModel();

            ViewBag.errorType = errorType; 
            ViewBag.errorMsg = errorMsg;

            List<User> users = _unitOfWork.UserRepos.GetAll().ToList();
            vm.Users = users;
            return View(vm);
        }

        [HttpPost]
        public IActionResult ConfigSave(int line_account_id, string profile_setting)
        {
            LineAccount model = _unitOfWork.LineAccountRepos.GetById(line_account_id);
            model.ProfileSetting = profile_setting;
            model.LineaccountUpdated = DateTime.Now;
            _unitOfWork.LineAccountRepos.Update(model);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Basic), new { errorType = "success", errorMsg = "登録が成功しました" });
        }

        [HttpPost]
        public IActionResult Save(LineAccount Account, IFormFile? cardDesign, IFormFile? logoImg) 
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = "登録が失敗しました" });

            if (cardDesign != null)
            {
                string cardValid = UploadFileValidation(cardDesign);
                if(!string.IsNullOrEmpty(cardValid))
                {
                    ModelState.AddModelError("", cardValid);
                    return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = cardValid });
                }
                if (!string.IsNullOrEmpty(Account.MembersCardDesignUrl))
                {
                    DeleteFile(Account.MembersCardDesignUrl);
                }
                string url = SaveUploadFile(cardDesign);
                Account.MembersCardDesignUrl = url;
            }

            if (logoImg != null)
            {
                string logoValid = UploadFileValidation(logoImg);
                if (!string.IsNullOrEmpty(logoValid))
                {
                    ModelState.AddModelError("", logoValid);
                    return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = logoValid });
                }
                if (!string.IsNullOrEmpty(Account.LineaccountLogoUrl))
                {
                    DeleteFile(Account.LineaccountLogoUrl);
                }
                string url = SaveUploadFile(logoImg);
                Account.LineaccountLogoUrl = url;
            }

            Account.LineaccountUpdated = DateTime.Now;
            _unitOfWork.LineAccountRepos.Update(Account);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index), new { errorType = "success", errorMsg = "登録が成功しました" });
        }

        [HttpPost]
        public async Task<IActionResult> UserSave(RegisterUserViewModel newUser)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index), new {errorType="error", errorMsg= "登録が失敗しました" });
            }
                

            if (newUser.UserRePwd != newUser.UserPwd)
            {
                return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = "値が違います" });
            }

            var atUser = await _unitOfWork.UserRepos.GetByCondition(u => u.UserLoginId == newUser.UserLoginId).FirstOrDefaultAsync();

            if (atUser != null)
            {
                return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = "その名前はすでに使用されています" });
            }

            atUser = await _unitOfWork.UserRepos.GetByCondition(u => u.UserEmail == newUser.UserEmail).FirstOrDefaultAsync();

            if (atUser != null)
            {
                return RedirectToAction(nameof(Index), new { errorType = "error", errorMsg = "そのメールアドレスは既に使用されています" });
            }
            User model = new User();

            model.UserName = newUser.UserName;
            model.UserLoginId = newUser.UserLoginId;
            model.UserEmail = newUser.UserEmail;
            model.UserPwd = AuthHelper.HashPassword(newUser.UserPwd);
            model.UserLineAccountRole = newUser.UserLineAccountRole;

            model.UserCreated = DateTime.Now;
            _unitOfWork.UserRepos.Add(model);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index), new { errorType = "success", errorMsg = "登録が成功しました" });
        }

        public IActionResult UserDelete(int userID)
        {

nxLINEadmin/Controllers/TradingHistoryController.cs
using AutoMapper;
using nxLINEadmin.ViewModels;
using Microsoft.AspNetCore.Mvc;
using nxLINEadmin.Entity;
using nxLINEadmin.UnitOfWork;
using Member = nxLINEadmin.Entity.Member;

namespace nxLINEadmin.Controllers
{
    public class TradingHistoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public TradingHistoryController(
            IUnitOfWork unitOfWork,
            IMapper mapper
            )
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

nxLINEadmin/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nxLINEadmin</title>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/css/app-creative.min.css" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/svg.css" asp-append-version="true" />
</head>
@using Microsoft.Extensions.Configuration
@{
    IConfiguration configuration = new ConfigurationBuilder()
        .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
        .AddJsonFile("appsettings.json")
        .Build();
}
<body class="login-body justify-content-center">
    <div class="login_container px-5">
        <div class="card shadow w-100">
            <div class="row no-gutters">
                <div class="col-md-6 d-none d-sm-block">
                    <img src="@configuration?["LoginSettings:LoginImagePath"]" alt="Login Image">
                </div>
                <div class="col-md-6 px-md-5 px-3">
                    <div class="my-4">
                        <img class="img-fluid px-5" src="@configuration?["LoginSettings:LogoPath"]">
                        <hr>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>       
</body>
</html>
@await RenderSectionAsync("Scripts", required: false)

nxLINEadmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="jp" data-layout="topnav">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - nxLINEadmin</title>

    <!-- Theme Config Js -->
    <script src="~/assets/js/hyper-config.js"></script>

    <!-- App css -->
    <link href="~/assets/css/app-creative.min.css" rel="stylesheet" type="text/css" id="app-style" />

    <!-- Icons css -->
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/dataTables.css" type="text/css" />
    <link rel="stylesheet" href="~/css/jquery.toast.min.css" type="text/css" />

    <!-- Custom css -->
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    <style>
        .container-fluid {
            max-width: 99% !important;
        }

    </style>
    @await RenderSectionAsync("Css", required: false)
</head>
<body>
    <!-- Begin page -->
    <div class="wrapper">
        <!-- ========== Topbar Start ========== -->
        <div class="navbar-custom">
            <div class="topbar container-fluid">
                <div class="d-flex align-items-center gap-lg-2 gap-1">
                    <!-- Topbar Brand Logo -->
                    <div class="logo-topbar">
                        <!-- Logo light -->
                        <a href="index.html" class="logo-light">
                            <span class="logo-lg">
                                <img src="/images/wide_logo.png" alt="logo">
                            </span>
                            <span class="logo-sm">
                                <img src="assets/images/logo-sm.png" alt="small logo">
                            </span>
                        </a>

                        <!-- Logo Dark -->
                        <a href="index.html" class="logo-dark">
                            <span class="logo-lg">
                                <img src="/images/wide_logo.png" alt="dark logo">
                            </span>
                            <span class="logo-sm">
                                <img src="assets/images/logo-dark-sm.png" alt="small logo">
                            </span>
                        </a>
                    </div>

                    <!-- Sidebar Menu Toggle Button -->
                    <button class="button-toggle-menu">
                        <i class="mdi mdi-menu"></i>
                    </button>
                    <!-- Horizontal Menu Toggle Button -->
                    <button class="navbar-toggle" data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </button>
                </div>
                <ul class="topbar-menu d-flex align-items-center gap-3">
                    <li class="d-none d-sm-inline-block">
                        <div class="nav-link" id="light-dark-mode" data-bs-toggle="tooltip" data-bs-placement="left" title="Theme Mode">
                            <i class="ri-moon-line font-22"></i>
                        </div>
                    </li>
                    <li class="d-md-inline-block">
                        <a asp-controller="Auth" asp-action="Logout" class="dropdown-item">
                            <i class="mdi mdi-logout font-22"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- ========== Topbar End ========== -->
        <!-- ========== Horizontal Menu Start ========== -->
        <div class="topnav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="topnav-menu-content">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index" id="topnav-dashboards" role="button">
                                    <i class="fad fa-analytics fa-lg"></i>ダッシュボード
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="customers" asp-action="Index" id="topnav-dashboards" role="button">
                                    <i class="fad fa-users fa-lg"></i>顧客管理
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="TradingHistory" asp-action="Index" id="topnav-dashboards" role="button">
                                    <i class="fad fa-list-ul fa-lg"></i>取引履歴
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index" id="topnav-dashboards" role="button">
                                    <i class="fa-duotone fa-ticket fa-lg"></i>クーポン
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index" id="topnav-dashboards" role="button">
                                    <i class="fad fa-poll-people fa-lg"></i>アンケート一覧
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-mdb-toggle="dropdown" id="navbarDropdown" aria-expanded="false" role="button">
                                    <i class="fa-solid fa-gear fa-lg"></i>設定
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Setting" asp-action="Basic" id="action1">基本情報</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Setting" asp-action="Membership"  id="action2">会員登録設定</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Setting" asp-action="Permission" id="action3">権限設定</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- ========== Horizontal Menu End ========== -->
        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <div class="content">

                <!-- Start Content-->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- container -->

            </div>
            <!-- content -->
            <!-- Footer Start -->
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
                        </div>
                        <div class="col-md-6">
                            <div class="text-md-end footer-links d-none d-md-block">
                                <a href="javascript: void(0);">About</a>
                                <a href="javascript: void(0);">Support</a>
                                <a href="javascript: void(0);">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- end Footer -->

        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->
    </div>
    <!-- Vendor js -->
    <script src="~/assets/js/vendor.min.js"></script>
    <!-- App js -->
    <script src="~/assets/js/app.min.js"></script>
    <script src="~/js/dataTables.js"></script>
    <script src="~/js/jquery.toast.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>